# Generated by Django 2.2.24 on 2021-12-05 20:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0002_auto_20211125_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 20, 34, 47, 93088, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
